### PR TITLE
Partially fixed load

### PR DESCRIPTION
**Pull request by jackwoodward**
omdbapi now requires two characters and a space isn't good enough

### CODE REVIEW

**Comment by jackwoodward** [comment]
I'm calling this partial because all it does is let the code work, less movies are loaded now. Only 97k.

**Comment by robdmoore** [comment]
Does the issue still occur when you run the simulation or not?

**Comment by japf** [comment]
A small update to confirm that:
1. The pull-request fixes the fact that no movies were loaded. As @jackwoodward said, about 97k movies are now loaded
2. The transient failure still occurs. Reproduced with a S3 SQL Azure DB and 4 Azure Websites.

**Comment by robdmoore** [comment]
Awesome! Thanks will merge.

**Pull request merged**
